version: '3'
services:
  postgres:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flask-app:
    container_name: flask-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/db
      SECRET_KEY: ${SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      PERMANENT_SESSIONLIFETIME: ${PERMANENT_SESSIONLIFETIME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./app:/app

volumes:
  postgres-data:
