services:
  postgres:
    container_name: db
    build:
      context: ./db 
      dockerfile: Dockerfile 
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  flask-app:
    container_name: flask-app
    build:
      context: ./app 
      dockerfile: Dockerfile  #
    ports:
      - "4000:4000" 
    environment:
      - FLASK_ENV=production 
      - DATABASE_URL=postgresql://admin:admin@db:5432/db 
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./app:/app
volumes:
  postgres-data:  
